Cognitive properties stable
rep2rep/robin pull request #21
Opened 2019-11-20 15:46 UTC by danielraggi

This has the code from cognitive properties, but not the testing files.
It adds patterns, cognitive properties, and updates many tables.

2019-11-20 15:47 UTC, danielraggi commented
oh, and I think it also includes the pseudo-Q table branch that we never merged into master.

2019-11-20 17:20 UTC, aaronstockdill requested changes
I have not checked the tables, as that will take a long time and I will only make things worse, not better.

I have not thoroughly gone over `pattern.sml` nor `cognitive.sml`. They both confuse me; perhaps in person would be better. 

The remaining issues are very minor, mostly just removing comments.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/importance.sml
> +    (*datatype importance = Noise | Zero | Low | Medium | High;*)
Can delete this commented line

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/importance.sml
> +  (*)  val fromReal : real -> importance;*)
Type alias is transparent, remove comment.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/importance.sml
> +datatype importance = Noise | Zero | Low | Medium | High;*)
Remove comment

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/importance.sml
> +*)
Please remove all the commented code.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/property.sml
> +                    else raise ((*print ("no tokens attribute for " ^ Kind.toString k ^ "-" ^ stringOfValue v) ; *)
Remove comment

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/property.sml
> +fun getNumFunction s (k, v,[]) = ((*print ("no numFunction attribute " ^ s ^ " for property " ^ Kind.toString k ^ "-" ^ stringOfValue v ^ "\n"); *)
Remove comment

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/property.sml
> +                (*)      SOME b' => (Property.fromString a, b')
Remove comment

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/readers.sml
> +      | stringProduct (s::L) L' = addPrefixToAll s L' @ stringProduct L L';
This is unnecessarily complicated:
```
val stringProduct = (map op^) o  List.cartesianProduct
```
and could thus be locally bound below.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/readers.sml
> +            val importance = if t = "error_allowed" then Importance.fromString "High" else if t = "mode" then Importance.fromString "Zero" else importanceOfPrefix p
Can just use `Importance.High` rather than `Importance.fromString "High"`, etc.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/readers.sml
> +        else Importance.fromString "Zero";
Can just use `Importance.High` rather than `Importance.fromString "High"`, etc.

2019-11-20 17:20 UTC, aaronstockdill commented on src/util/multiset.sml
> +fun size xs = D.foldr (fn ((x, i), v) => if i >=0 then i + v else Int.min (i,v)) 0 xs; (* note that negative multiplicities are taken as "infinite", and smaller negatives are larger cardinal infinite
I don't love this being here, but I understand why it has to be. Leave it until we have a better solution.

2019-11-20 17:20 UTC, aaronstockdill commented on src/util/robinlib.sml
> +
Can probably just name this `product`.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/readers.sml
> +      | stringProduct (s::L) L' = addPrefixToAll s L' @ stringProduct L L';
(Note that I suggest renaming `cartesianProduct` to just `product`; the idea holds.

2019-11-20 17:20 UTC, aaronstockdill commented on src/util/robinlib.sml
> +    end;
```
fun weightedSumIndexed w f L =
    List.foldr (fn (x, s) => ((w x) * (f x)) + s) 0.0 L;
```

2019-11-20 17:20 UTC, aaronstockdill commented on src/util/robinlib.sml
> +    end;
I find this slightly less confusing, as it makes clearer that the `w` and `f` are always applying to the same element.

2019-11-20 17:20 UTC, aaronstockdill commented on src/util/set.sml
> +    val foldr: (t * 'a -> 'a) -> 'a -> t set -> 'a;
The space before the colon should not have been stripped.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/tables.sml
> +                              | NONE => raise TableError ("Unknown importance '" ^ s ^ "'");*)
Remove comment.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/tables.sml
> +                  | NONE => ((fn s => [(Property.Label s,[])]), (Kind.fromString key), Importance.fromString "Low");
Why was this replaced? The old version was better, I think.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/tables.sml
> +                findName propertyKinds (*(List.filter notRelated propertyKinds)*) (* probably not necessary to filter now*)
Remove comment.

2019-11-20 17:20 UTC, aaronstockdill commented on src/strategies/properties/tables.sml
> +                fun notRelated (_, _, x) = not (String.isSubstring "_related_" x);
Unused: remove.

2019-11-21 10:02 UTC, danielraggi commented
I've done all the changes requested

2019-11-21 10:05 UTC, danielraggi commented
sorry, not all. I missed a couple

2019-11-21 10:29 UTC, danielraggi commented on src/strategies/properties/readers.sml
> +      | stringProduct (s::L) L' = addPrefixToAll s L' @ stringProduct L L';
suggestion was wrong because of composition with 2 arguments. Chaged the product function to make it right.

2019-11-21 10:55 UTC, aaronstockdill approved these changes

2019-11-21 10:55 UTC, merged